Data loading & Exploration

In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv(r'C:\Users\sheri\Desktop\machinlearning\data\raw_data\AmericanElectricPower_hourly.csv')
df.shape

(121273, 2)

In [3]:
df.head()

              Datetime   AEP_MW
0  2004-12-31 01:00:00  13478.0
1  2004-12-31 02:00:00  12865.0
2  2004-12-31 03:00:00  12577.0
3  2004-12-31 04:00:00  12517.0
4  2004-12-31 05:00:00  12670.0

In [4]:
pd.set_option('display.max_columns', None)    # Show all columns in the DataFrame
pd.set_option('display.max_rows', None)      # Show all rows in the DataFrame

In [5]:
df.describe(include = 'all')

                   Datetime         AEP_MW
count                121273  121273.000000
unique               121269            NaN
top     2014-11-02 02:00:00            NaN
freq                      2            NaN
mean                    NaN   15499.513717
std                     NaN    2591.399065
min                     NaN    9581.000000
25%                     NaN   13630.000000
50%                     NaN   15310.000000
75%                     NaN   17200.000000
max                     NaN   25695.000000

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 121273 entries, 0 to 121272
Data columns (total 2 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   Datetime  121273 non-null  object
 1   AEP_MW    121273 non-null  float64
dtypes: float64(1), object(1)
memory usage: 1.9+ MB

In [7]:
df['Datetime'] = pd.to_datetime(df['Datetime'])
print(df['Datetime'].dt.year.value_counts())

Datetime
2016    8784
2008    8782
2012    8781
2017    8760
2015    8760
2014    8759
2006    8758
2005    8758
2011    8758
2007    8758
2009    8758
2013    8758
2010    8757
2018    5136
2004    2206
Name: count, dtype: int64

Avoid Data Leakage
1. Train set (2004-2011) is clean historical training
2. Eval set (2012-2015) is unseen during training, but used for validation and hyperparameter tuning
3. Holdout set (2016-2018) is completely untouched until the very end

In [8]:
# Sort by date (important to avoid shuffling issues)
df = df.sort_values("Datetime")

In [9]:
# Define cutoff dated
cutoff_date_eval = "2012-01-01" # validation start
cutoff_date_holdout = "2016-01-01"

In [10]:
# Train: before 2012
train_df = df[df["Datetime"] < cutoff_date_eval]

# Validation/Eval: 2012 - 2015
eval_df = df[
    (df["Datetime"] >= cutoff_date_eval) & 
    (df["Datetime"] < cutoff_date_holdout)
]

# Holdout: 2016 - 2018
holdout_df = df[df["Datetime"] >= cutoff_date_holdout]

print("Train shape:", train_df.shape)
print("Eval shape:", eval_df.shape)
print("Holdout shape", holdout_df.shape)

Train shape: (63535, 2)
Eval shape: (35058, 2)
Holdout shape (22680, 2)

In [11]:
# Save splits
train_df.to_csv(r"C:\Users\sheri\Desktop\machinlearning\data\raw_data\train.csv", index=False)
eval_df.to_csv(r"C:\Users\sheri\Desktop\machinlearning\data\raw_data\eval.csv", index=False)
holdout_df.to_csv(r"C:\Users\sheri\Desktop\machinlearning\data\raw_data\holdout.csv", index=False)